config/routes.rb
Rails.application.routes.draw do
  
  resources :categories, only: [:index, :show]
  resources :products, only: [:index, :show]


  namespace :admin do
    root 'categories#index'
    resources :categories do 
      resources :products
    end
  end
  
  root 'pages#index'
  get 'pages/index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
module Admin
  def self.table_name_prefix
    'admin_'
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  belongs_to :parent_category, class_name: 'Category', optional: true
  has_many :child_categories, 
  			class_name: 'Category', 
  			foreign_key: 'parent_category_id', 
  			dependent: :destroy
  has_many :products
end

app/models/picture.rb
class Picture < ApplicationRecord
	belongs_to :product
	has_attached_file :image,
                    styles: { medium: '300x300>', thumb: '100x100>'},
                    default_url: '/images/:style/missing.png'
  	validates_attachment_content_type :image, 
                    content_type: ['image/jpeg', 'image/gif', 'image/png']

                    
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :category
  has_many :pictures
  accepts_nested_attributes_for :pictures, reject_if: :all_blank, allow_destroy: true
end

app/controllers/admin/categories_controller.rb
class Admin::CategoriesController < AdminController

  before_action :set_admin_category, only: [:show, :edit, :update, :destroy]

  # GET /admin/categories
  # GET /admin/categories.json
  def index
    @admin_categories = Category.order('parent_category_id ASC')
  end

  # GET /admin/categories/1
  # GET /admin/categories/1.json
  def show
    @product = Product.new
  end

  # GET /admin/categories/new
  def new
    @admin_category = Category.new
  end

  # GET /admin/categories/1/edit
  def edit
  end

  # POST /admin/categories
  # POST /admin/categories.json
  def create
    @admin_category = Category.new(admin_category_params)

    respond_to do |format|
      if @admin_category.save
        format.html { redirect_to [:admin, @admin_category], notice: 'Category was successfully created.' }
        format.json { render :show, status: :created, location: @admin_category }
      else
        format.html { render :new }
        format.json { render json: @admin_category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /admin/categories/1
  # PATCH/PUT /admin/categories/1.json
  def update
    respond_to do |format|
      if @admin_category.update(admin_category_params)
        format.html { redirect_to [:admin, @admin_category], notice: 'Category was successfully updated.' }
        format.json { render :show, status: :ok, location: @admin_category }
      else
        format.html { render :edit }
        format.json { render json: @admin_category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /admin/categories/1
  # DELETE /admin/categories/1.json
  def destroy
    @admin_category.destroy
    respond_to do |format|
      format.html { redirect_to admin_categories_url, notice: 'Category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_admin_category
      @admin_category = Category.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def admin_category_params
      params.require(:category).permit(:name, :description, :parent_category_id)
    end
end

app/controllers/admin/products_controller.rb
class Admin::ProductsController < AdminController
  before_action :set_category
	before_action :set_product, only: [:show, :edit, :update, :destroy]

  def show
  end

  def new
    @product = Product.new
    @product.pictures.new
  end

  # GET /admin/products/1/edit
  def edit
  end

  # POST /admin/products
  # POST /admin/products.json
  def create
    @product = @category.products.build(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to [:admin, @category, @product], notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /admin/products/1
  # PATCH/PUT /admin/products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to [:admin, @category, @product], notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /admin/products/1
  # DELETE /admin/products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to admin_products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

    def set_category
      @category = Category.find(params[:category_id])
    end
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:title, :details, :category_id, :price, pictures_attributes: [:title, :image])
    end
end

app/controllers/admin_controller.rb
class AdminController < ActionController::Base
	layout 'admin'
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def index
  end

  def show
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index

  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
  	@products = Product.all
  	@categories = Category.where(parent_category_id: nil)
  	@categories.each do |cat|
  		p cat.name
  	end
  end

  def show
    
  end
end

app/helpers/admin/categories_helper.rb
module Admin::CategoriesHelper
end

app/helpers/admin/products_helper.rb
module Admin::ProductsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/admin/categories/_categories.html.erb
<ol>
  <% categories.each do |category| %>
    <li>
       <%= link_to category.name, admin_category_path(category) %> 
      <% if category.child_categories.any? %>
          <%= render 'admin/categories/categories', categories: category.child_categories %>
      <% end %>
    </li>
  <% end %>
</ol>

app/views/admin/categories/_form.html.erb
<%= form_for([:admin, admin_category]) do |f| %>
  <% if admin_category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(admin_category.errors.count, "error") %> prohibited this admin_category from being saved:</h2>

      <ul>
      <% admin_category.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name, 'Название' %>
    <%= f.text_field :name, class: 'form-control' %>
  </div>

  <div class="field">
    <%= f.label :description, 'Описание' %>
    <%= f.text_area :description, class: 'form-control' %>
  </div>

  <div class="field">
    <%= f.label :parent_category_id, 'Вложить в категорию:' %>
    <%= f.collection_select :parent_category_id, Category.order('parent_category_id ASC'), :id, :name, {:include_blank => true}, class: 'form-control' %>
  </div>
  <hr>
  <div class="actions">
    <%= f.submit class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/admin/categories/edit.html.erb
<h1>Editing Admin Category</h1>

<%= render 'form', admin_category: @admin_category %>

<%= link_to 'Show', @admin_category %> |
<%= link_to 'Back', admin_categories_path %>

app/views/admin/categories/index.html.erb
<p id="notice"><%= notice %></p>



<div class="panel panel-primary">
  <!-- Default panel contents -->
  <div class="panel-heading">Категории товаров</div>
  <div class="panel-body">
    <p>
      <%= link_to 'Добавить новую', new_admin_category_path, class: 'btn btn-default' %>
    </p>
  </div>

  <!-- Table -->
  <table class="table table-condensed">
    <thead>
        <tr>
          <th>Название</th>
          <th>Описание</th>
          <th>Родитель</th>
          <th colspan="2"></th>
        </tr>
      </thead>

      <tbody>
        <% @admin_categories.each do |admin_category| %>
          <tr>
            <td><%= link_to admin_category.name, admin_category_path(admin_category) %></td>
            <td><%= admin_category.description %></td>
            <td><%= admin_category.parent_category.name if admin_category.parent_category %></td>
            
            <td><%= link_to 'Edit', edit_admin_category_path(admin_category) %></td>
            <td><%= link_to 'Destroy', admin_category, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          </tr>
        <% end %>
      </tbody>
  </table>
</div>

app/views/admin/categories/new.html.erb
<div class="panel panel-primary">
  <div class="panel-heading">
    <h3 class="panel-title">Добавить новую категорию</h3>
  </div>
  <div class="panel-body">

    <%= render 'form', admin_category: @admin_category %>
	<%= link_to 'Back', admin_categories_path %>

  </div>
</div>

app/views/admin/categories/show.html.erb
<div class="container">
	<p id="notice"><%= notice %></p>

	<h2>
	  <strong>Категория:</strong>
	  <%= @admin_category.name %>
	</h2>

	<style type="text/css">
		p {
			margin: 10px;
		}
	</style>

	<div class="row">
		<div class="col-sm-6">
			<p>
				<strong>Description:</strong>
				<%= @admin_category.description %>
			</p>

			<p>
				<strong>Parent category:</strong>
				<%= @admin_category.parent_category.name if @admin_category.parent_category %>
			</p>

			<%= link_to 'Edit', edit_admin_category_path(@admin_category) %> |
			<%= link_to 'Back', admin_categories_path %>
			
			
		</div>

		

		<div class="col-sm-6">
			<h5>
				<%= link_to "Добавить товар в #{@admin_category.name}", new_admin_category_product_path(@admin_category), class: 'btn btn-success' %>
			</h5>

			<h3 style="margin: 20px 0 20px 0;">Товары в данной категории::</h3>
			<hr>
			<ul>
				<% @admin_category.products.each do |pr| %>
				<li>
					<%= link_to pr.title + '555', admin_category_product_path(@admin_category, pr) %> 
				</li>
				<% end %>
			</ul>
			
				
				
			


		</div>

	</div>
</div>

app/views/admin/products/_form.html.erb
<%= form_for([:admin, @category, @product]) do |f| %>
  <% if @product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@product.errors.count, "error") %> prohibited this @product from being saved:</h2>

      <ul>
      <% @product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title, class: 'form-control' %>
  </div>
  <div class="field">
    <%= f.label :price %>
    <%= f.number_field :price, class: 'form-control' %>
  </div>

  <div class="field">
    <%= f.label :details %>
    <%= f.text_area :details, class: 'form-control' %>
  </div>

  
  <div id='pictures' style="border: solid 2px green; padding: 10px; margin: 20px;">
    <p><strong>Добавить рисунки:</strong></p>
    <%= f.fields_for :pictures do |picture| %>
      <%= render 'picture_fields', :f => picture %>
    <% end %>

    <div class='links'>
    <hr>
      <%= link_to_add_association 'Еще изображение', f, :pictures, class: 'btn btn-primary' %>
    </div>
  </div>
  <hr>

  <div class="actions">
    <%= f.submit class: 'btn btn-default' %>
  </div>
<% end %>

app/views/admin/products/_picture_fields.html.erb
<div class='nested-fields row'>
  <div class="field col-sm-7">
    <%= f.label :title %>
    <%= f.text_field :title, class: 'form-control'  %>
  </div>
  <div class="field col-sm-3">
    <%= f.label :image %>
    <%= f.file_field :image %>
  </div>
  <div class="col-sm-2">
    <%= link_to_remove_association "Удалить поле", f, class: 'btn btn-danger' %>
  </div>
  
</div>

app/views/admin/products/edit.html.erb
<h1>Edit product</h1>
<%= render 'form' %>

app/views/admin/products/new.html.erb
<h1>New product</h1>
<%= render 'form' %>

app/views/admin/products/show.html.erb
<h1><%= @product.title %></h1>
<p><%= @product.price %></p>
<p>
<% @product.pictures.each do |pic| %>
	<%= image_tag pic.image.url(:thumb) %> <hr>
<% end %>
	
</p>

<p>
	<%= link_to 'Edit', edit_admin_category_product_path(@product) %>
	<%= link_to 'Destroy', admin_category_product_path(@product), method: :delete %>
</p>

app/views/categories/show.html.erb
<h1>Categories#show</h1>
<p>Find me in app/views/categories/show.html.erb</p>

app/views/layouts/_navbar.html.erb
<!-- header-section-starts -->
<div class="c-header" id="home">
  <div class="top-header">
    <div class="container">

      <div class="logo">
        <%= link_to(image_tag('logo.png')) %>
      </div>

      <div class="header-top-right">
        <!-- start search-->
        <div class="search-box">
          <div id="sb-search" class="sb-search">
            <form>
              <input class="sb-search-input" placeholder="Enter your search term..." type="search" name="search" id="search">
              <input class="sb-search-submit" type="submit" value="">
              <span class="sb-icon-search"> </span>
            </form>
          </div>
        </div>

        <!-- search-scripts -->
       
        <script>
          new UISearch(document.getElementById('sb-search'));
        </script>

        <!-- //search-scripts -->

        <a href="cart.html"><i class="cart"></i></a>
      </div>
      <div class="navigation">
        <div>
          <label class="mobile_menu" for="mobile_menu">
            <span>Menu</span>
          </label>
          <input id="mobile_menu" type="checkbox">
          <ul class="nav">
            <li class="active"><a href="/">Home</a></li>

             <% Category.where( parent_category: nil ).each do |category| %>
              
                <li class="dropdown1">
                  <%= link_to category.name, category_path(category) %>
                  
                    <ul class="dropdown2">
                      <% category.child_categories.each do |c| %>
                           <li><%= link_to c.name, category_path(c) %></li>
                      <% end %>
                    </ul>
                  
                </li>
              
            <% end %>



            <li><a href="contact.html">Contact US</a></li>
            <div class="clearfix"></div>
          </ul>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Admin</title>
    <%= csrf_meta_tags %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
 




<!-- header-section-starts -->
<div class="c-header" id="home">
  <div class="top-header">
    <div class="container">

      <div class="logo">
        <%= link_to(image_tag('logo.png'), root_path) %>
      </div>

      <div class="header-top-right">
        <!-- start search-->
        <div class="search-box">
          <div id="sb-search" class="sb-search">
            <form>
              <input class="sb-search-input" placeholder="Enter your search term..." type="search" name="search" id="search">
              <input class="sb-search-submit" type="submit" value="">
              <span class="sb-icon-search"> </span>
            </form>
          </div>
        </div>

        <!-- search-scripts -->
       
        <script>
          new UISearch(document.getElementById('sb-search'));
        </script>

        <!-- //search-scripts -->

        <a href="cart.html"><i class="cart"></i></a>
      </div>
      <div class="navigation">
        <div>
          <label class="mobile_menu" for="mobile_menu">
            <span>Menu</span>
          </label>
          <input id="mobile_menu" type="checkbox">
          <ul class="nav">
            <li class="active">
              <%= link_to 'Admin root', admin_root_path %>
            </li>

             <% Category.where( parent_category: nil ).each do |category| %>
              
                <li class="dropdown1">
                  <%= link_to category.name, admin_category_path(category) %>
                  
                    <ul class="dropdown2">
                      <% category.child_categories.each do |c| %>
                           <li><%= link_to c.name, admin_category_path(c) %></li>
                      <% end %>
                    </ul>
                  
                </li>
              
            <% end %>



            <li></li>
            <div class="clearfix"></div>
          </ul>
        </div>
      </div>
    </div>
  </div>
</div>

<div style="margin-left: 10px; margin-right: 10px;">
  <div class="row">
    <div class="col-sm-3">
    <hr>      


        <div class="panel panel-primary" id="cart">
          <div class="panel-heading">
            <h3 class="panel-title">Вложенность категорий</h3>
          </div>
          <div class="panel-body">
            <%= render 'admin/categories/categories', categories: Category.where(parent_category: nil) %>
          </div>
        </div>

      
    </div>
    <div class="col-sm-9">
    <hr>
      <%= yield %>
    </div>
  </div>
   
</div>
    
    
</body>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Shop - Market</title>
    <%= csrf_meta_tags %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <%= yield %>
  </body>
</html>

app/views/products/index.html.erb
<!-- start Dresses-page -->

<!-- content-section-starts -->
<div class="container">
  <div class="dreamcrub">
    <ul class="breadcrumbs">

      <li class="home">
        <a href="index.html" title="Go to Home Page"><%= image_tag 'home.png' %></a>&nbsp;
        <span>&gt;</span>
      </li>
      <li>
        Dresses
        <span>&gt;</span>
      </li>
      <li>
        <span class="red">&nbsp;Clothes&nbsp;</span>
      </li>
    </ul>
    <ul class="previous">
      <li><a href="index.html">Back to Previous Page</a></li>
    </ul>
    <div class="clearfix"></div>
  </div>
</div>
<div class="container">
  <div class="ft-ball">
    <div class="cont span_2_of_3">
      <div class="mens-toolbar">
        <div class="sort">
          <div class="sort-by">
            <label>Sort By</label>
            <select>
              <option value="">
                Popularity
              </option>
              <option value="">
                Price : High to Low
              </option>
              <option value="">
                Price : Low to High
              </option>
            </select>
            <a href=""><%= link_to image_tag 'arrow2.gif', class: 'v-middle' %></a>
          </div>
        </div>
        <div class="pager">
          <div class="limiter visible-desktop">
            <label>Show</label>
            <select>
              <option value="" selected="selected">
                9
              </option>
              <option value="">
                15
              </option>
              <option value="">
                30
              </option>
            </select> per page
          </div>
          <ul class="dc_pagination dc_paginationA dc_paginationA06">
            <li><a href="#" class="previous">Pages</a></li>
            <li><a href="#">1</a></li>
            <li><a href="#">2</a></li>
          </ul>
          <div class="clearfix"></div>
        </div>
        <div class="clearfix"></div>
      </div>

<!-- one product -->
      <div class="box1">
        
        <% @products.each do |product| %>
        
          <div class="col_1_of_single1 span_1_of_single1">
            <div class="view1 view-fifth1">
              <div class="top_box">
                <h3 class="m_1"><%= product.title %></h3>
                <p class="m_2"><%= product.category.name %></p>
                <a href="single.html">
                  <div class="grid_img">
                    <div class="css3">
                    
                    <%= image_tag(product.pictures.first.image.url, width: 235, height: 315) %>
                      
                    </div>
                    <div class="mask1">
                      <div class="info">Quick View</div>
                    </div>
                  </div>
                  <div class="price">$ 510</div>
              </div>
            </div>
            </a>
            <div class="rtng">
              <form action="" class="sky-form">
                <fieldset>
                  <section>
                    <div class="rating">
                      <input type="radio" name="stars-rating" id="stars-rating-5">
                      <label for="stars-rating-5"><i class="icon-star"></i></label>
                      <input type="radio" name="stars-rating" id="stars-rating-4">
                      <label for="stars-rating-4"><i class="icon-star"></i></label>
                      <input type="radio" name="stars-rating" id="stars-rating-3">
                      <label for="stars-rating-3"><i class="icon-star"></i></label>
                      <input type="radio" name="stars-rating" id="stars-rating-2">
                      <label for="stars-rating-2"><i class="icon-star"></i></label>
                      <input type="radio" name="stars-rating" id="stars-rating-1">
                      <label for="stars-rating-1"><i class="icon-star"></i></label><span class="rtng">(5)<span>
                    <div class="clearfix"></div>
                    </div>
                  </section>
                </fieldset>
              </form>
            </div>
            <ul class="list2">
              <li>
                <%= image_tag 'plus.png' %>
                <ul class="icon1 sub-icon1 profile_img">
                  <li><a class="active-icon c1" href="single.html">Add To Bag </a>
                    <ul class="sub-icon1 list">
                      <li><h3>sed diam nonummy</h3><a href=""></a></li>
                      <li><p>Это высплывающее окно <a href="">adipiscing elit, sed diam</a></p></li>
                    </ul>
                  </li>
                </ul>
              </li>
            </ul>
            <div class="clear"></div>
          </div>

        <% end %>
      </div>
<!-- end of the one product -->

    </div>
    <div class="rsidebar span_1_of_left">
      <section class="sky-form">
        <div class="product_right">
          <h3 class="m_2">Категории</h3>
          <% Category.where(parent_category_id: nil).each do |category| %>
          <select class="dropdown" tabindex="10" data-settings='{"wrapperClass":"metro"}'>
            <% counter = 0 %>
            <option value="<%= counter %>"><%= category.name %></option>
            <% category.child_categories.each do |child| %>

              <option value="<%= counter %>"><%= child.name %></option>
              <% counter += 1 %>
            <% end %>
          </select>
          <% end %>

        </div>
        <h4>Occasion</h4>
        <div class="row row1 scroll-pane">
          <div class="col col-4">
            <label class="checkbox"><input type="checkbox" name="checkbox" checked=""><i></i>Athletic (20)</label>
          </div>
          <div class="col col-4">
            <label class="checkbox"><input type="checkbox" name="checkbox"><i></i>Athletic Shoes (48)</label>
            <label class="checkbox"><input type="checkbox" name="checkbox"><i></i>Casual (45)</label>
            <label class="checkbox"><input type="checkbox" name="checkbox"><i></i>Casual (45)</label>
            <label class="checkbox"><input type="checkbox" name="checkbox"><i></i>Other (1)</label>
          </div>
        </div>
        <h4>Styles</h4>
        <div class="row row1 scroll-pane">
          <div class="col col-4">
            <label class="checkbox"><input type="checkbox" name="checkbox" checked=""><i></i>Athletic (20)</label>
          </div>
          <div class="col col-4">
            <label class="checkbox"><input type="checkbox" name="checkbox"><i></i>Ballerina (5)</label>
            <label class="checkbox"><input type="checkbox" name="checkbox"><i></i>Pumps (7)</label>
            <label class="checkbox"><input type="checkbox" name="checkbox"><i></i>High Tops (2)</label>
            <label class="checkbox"><input type="checkbox" name="checkbox"><i></i>Other (1)</label>
          </div>
        </div>
      </section>
      <section class="sky-form">
        <h4>Brand</h4>
        <div class="row row1 scroll-pane">
          <div class="col col-4">
            <label class="checkbox"><input type="checkbox" name="checkbox" checked=""><i></i>Adidas by Stella McCartney</label>
          </div>
          <div class="col col-4">
            <label class="checkbox"><input type="checkbox" name="checkbox"><i></i>Asics</label>
            <label class="checkbox"><input type="checkbox" name="checkbox"><i></i>Bloch</label>
            <label class="checkbox"><input type="checkbox" name="checkbox"><i></i>Bloch Kids</label>
            <label class="checkbox"><input type="checkbox" name="checkbox"><i></i>Capezio</label>
            <label class="checkbox"><input type="checkbox" name="checkbox"><i></i>Capezio Kids</label>
            <label class="checkbox"><input type="checkbox" name="checkbox"><i></i>Nike</label>
            <label class="checkbox"><input type="checkbox" name="checkbox"><i></i>Zumba</label>
          </div>
        </div>
      </section>
      <section class="sky-form">
        <h4>Heel Height</h4>
        <div class="row row1 scroll-pane">
          <div class="col col-4">
            <label class="checkbox"><input type="checkbox" name="checkbox" checked=""><i></i>Flat (20)</label>
          </div>
          <div class="col col-4">
            <label class="checkbox"><input type="checkbox" name="checkbox"><i></i>Under 1in(5)</label>
            <label class="checkbox"><input type="checkbox" name="checkbox"><i></i>1in - 1 3/4 in(5)</label>
            <label class="checkbox"><input type="checkbox" name="checkbox"><i></i>2in - 2 3/4 in(3)</label>
            <label class="checkbox"><input type="checkbox" name="checkbox"><i></i>3in - 3 3/4 in(2)</label>
          </div>
        </div>
      </section>
      <section class="sky-form">
        <h4>Price</h4>
        <div class="row row1 scroll-pane">
          <div class="col col-4">
            <label class="checkbox"><input type="checkbox" name="checkbox" checked=""><i></i>$50.00 and Under
              (30)</label>
          </div>
          <div class="col col-4">
            <label class="checkbox"><input type="checkbox" name="checkbox"><i></i>$100.00 and Under (30)</label>
            <label class="checkbox"><input type="checkbox" name="checkbox"><i></i>$200.00 and Under (30)</label>
            <label class="checkbox"><input type="checkbox" name="checkbox"><i></i>$300.00 and Under (30)</label>
            <label class="checkbox"><input type="checkbox" name="checkbox"><i></i>$400.00 and Under (30)</label>
          </div>
        </div>
      </section>
      <section class="sky-form">
        <h4>Colors</h4>
        <div class="row row1 scroll-pane">
          <div class="col col-4">
            <label class="checkbox"><input type="checkbox" name="checkbox" checked=""><i></i>Red</label>
          </div>
          <div class="col col-4">
            <label class="checkbox"><input type="checkbox" name="checkbox"><i></i>Green</label>
            <label class="checkbox"><input type="checkbox" name="checkbox"><i></i>Black</label>
            <label class="checkbox"><input type="checkbox" name="checkbox"><i></i>Yellow</label>
            <label class="checkbox"><input type="checkbox" name="checkbox"><i></i>Orange</label>
          </div>
        </div>
      </section>
    </div>
    <div class="clearfix"></div>
  </div>
</div>
<!-- content-section-ends -->


<div class="footer">
  <div class="up-arrow">
    <a class="scroll" href="#home"><%= image_tag 'up.png' %></a>
  </div>
  <div class="container">
    <div class="copyrights">
      <p>Copyright &copy; 2015 All rights reserved | Template by <a href="http://w3layouts.com"> W3layouts</a></p>
    </div>
    <div class="footer-social-icons">
      <a href="#"><i class="fb"></i></a>
      <a href="#"><i class="tw"></i></a>
      <a href="#"><i class="in"></i></a>
      <a href="#"><i class="pt"></i></a>
    </div>
    <div class="clearfix"></div>
  </div>
</div>